### ISSUE TITLE
PERUSAHAAN

### ISSUE THREAD

**Issue by totomaryoto** [bobykurniawan11/panorama#1]
![gambar](https://user-images.githubusercontent.com/61762120/79330519-e3d2c980-7f43-11ea-9c49-3a2c45d0f9ed.png)

ada penambahan field Provinsi sama kota/kabupaten
isiannya combobox baca dari tabel master provinsi dan kabupaten

perubahan type data grossup, jadi bit, isinya true/false

unutk kodeIndustri juga ambil dari masterindustri 

sp master industri & perusahaan pake ini aja
---CARA EXEC 
EXEC spInsMasterIndustri  'JASA',1,2,'IT'
EXEC spInsMasterIndustri @Deskripsi= 'OTOMOTIF',
@AktifStatus=1,@PersenJKK=2,@CreatedBy='IT'
									 
									 
									 
									 
exec	 spInsPerusahaan  @NamaPerusahaan ='PT AJI MUMPUNG',@NPWPPerusahaan ='1231422',
@NamaPimpinan ='MANDOR BAGUS',@NPWPPimpinan ='69',
@CutOff ='2020-01-15', @GrossUp=1,@AktifStatus =1,
@KodeIndustri ='INDUSTRI-AD-4',  --- Ini baca dari masterINdustri
@LokasiPerusahaan ='BEKASI',@provinsi ='11',@kotaKabupaten='1101',
@Alamat ='Jl aceh utara',@CreatedBy='it'

**Comment by bobykurniawan11** [comment]
tambahin provinsi & kabupaten
