### ISSUE TITLE
buat liat kodeGrossup ga bisa diklik

### ISSUE THREAD

**Issue by totomaryoto** [bobykurniawan11/panorama#10]
![gambar](https://user-images.githubusercontent.com/61762120/79639942-f4d84080-81b8-11ea-8507-7e23c7caa3b6.png)

**Comment by bobykurniawan11** [comment]
di cek lg ya

**Comment by totomaryoto** [comment]
grossup bisa diklik , tapi masuk nya ke list kabupaten

**Comment by bobykurniawan11** [comment]
cek lagi, kalo udah di close ya
