### ISSUE TITLE
Import Komponen Gaji Karayawan

### ISSUE THREAD

**Issue by totomaryoto** [bobykurniawan11/panorama#11]
Penambahan validasi Data Importan

spInsKomponenGajiKaryawan
(@kodePerusahaan varchar(32), @NIK varchar(32),@KodeKomponenGaji varchar(32),@JenisKomponen varchar(50),@Jumlah decimal(18,2), 
 @CreatedBy varchar(32),@Id varchar(50))
as

**Comment by bobykurniawan11** [comment]
cek lg yak

**Comment by totomaryoto** [comment]
https://drive.google.com/file/d/1XPQVRAl0t5tSLnLdFFwk-Iz9BgjfQaWR/view?usp=sharing

coba import pake ini, 
sukses tapi data ga masuk

**Comment by totomaryoto** [comment]
FormatDownloadtannya

**Comment by totomaryoto** [comment]
sama pas importnya


https://drive.google.com/file/d/1wni2SYUP6FRNEfMImdjY8U4kVPHdGOSb/view?usp=sharing

**Comment by bobykurniawan11** [comment]
pindahin ke sini ya https://github.com/bobykurniawan11/panorama/issues/13
