### ISSUE TITLE
Ubah/input karyawan

### ISSUE THREAD

**Issue by totomaryoto** [bobykurniawan11/panorama#20]
![gambar](https://user-images.githubusercontent.com/61762120/82850660-7729f200-9f27-11ea-9e61-4cb5cb874ca5.png)

ada keterang pilih item pada daftar,
tapi ga tau yang mana..
klo bisa focusnya diarahin ke yg salah . biar user langsung tau

**Comment by bobykurniawan11** [comment]
error dari plugin
