### ISSUE TITLE
http://panorama.rpgroup.co.id/Komponengajikaryawan

### ISSUE THREAD

**Issue by totomaryoto** [bobykurniawan11/panorama#8]
pada saat milih komponon, descripsinya ditampilin juga 

![gambar](https://user-images.githubusercontent.com/61762120/79639367-abd2bd00-81b5-11ea-9ed0-a970397633be.png)

**Comment by totomaryoto** [comment]
![gambar](https://user-images.githubusercontent.com/61762120/79639431-ffdda180-81b5-11ea-9c55-dc16eb1a638b.png)


data komponen harus sesuai dengan perusahaan yg dipilih . tidak tampil semua

**Comment by bobykurniawan11** [comment]
Di cek lagi ya

**Comment by totomaryoto** [comment]
![gambar](https://user-images.githubusercontent.com/61762120/79676466-c8501300-8210-11ea-89d6-d6d21bebb06c.png)

pas pilih NIK , ada NIK sama nama karyawanya  
misal TOTO(1603240)
         BOBY(1242352)
       BAGUS(124234)

**Comment by bagussus1911** [comment]
![image](https://user-images.githubusercontent.com/63939447/79678133-4f59b700-8222-11ea-931e-93873552789e.png)

Di cek lagi ya To

**Comment by bobykurniawan11** [comment]
cek lg , klo udah di close
