### ISSUE TITLE
import master karyawan

### ISSUE THREAD

**Issue by totomaryoto** [bobykurniawan11/panorama#9]
jika data sudah ada, tambahnkan message nya

**Comment by totomaryoto** [comment]
exec [spInsKaryawanImport]
(@KodePerusahaan varchar(32),
@Nama varchar(50),
@Alamat varchar(100),
@JenisKelamin varchar(20),
@NPWP varchar(32),
@TaxStatus varchar(32)
,@NIKKTPPaspor varchar(32),
@NIKKaryawan varchar(32),
@Kewarganegaraan varchar(32)
,@KodeDivisi varchar(32),
@KodeJabatan varchar(32),
@KodeNegara varchar(32),
@StatusKaryawan varchar(32),
@TMK date,
@GrossUp varchar(32),
@GajiPokok decimal(18,2),
@PengkaliNorma decimal(18,2),
@FlagUMR bit,
@AktifStatus bit,
@CreatedBy varchar(32)

**Comment by bobykurniawan11** [comment]
cek lg ya

**Comment by totomaryoto** [comment]
https://drive.google.com/file/d/1XPQVRAl0t5tSLnLdFFwk-Iz9BgjfQaWR/view?usp=sharing

coba import pake ini,
sukses tapi data ga masuk

**Comment by bobykurniawan11** [comment]
pindahin ke sini https://github.com/bobykurniawan11/panorama/issues/13
